# Use pre-built images from GitHub Container Registry
image:
  aarch64: ghcr.io/dueckminor/home-assistant-addons-mqtt-bridge:0.1.0-arm64
  amd64: ghcr.io/dueckminor/home-assistant-addons-mqtt-bridge:0.1.0-amd64