#!/bin/bash
# Script to extract a value from Home Assistant's secrets.yaml

set -eou pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "${ROOT_DIR}"

HOMEASSISTANT=homeassistant.local
if [[ -f "${ROOT_DIR}/gen/ha.txt" ]]; then
    HOMEASSISTANT=$(cat "${ROOT_DIR}/gen/ha.txt")
fi

ssh hassio@${HOMEASSISTANT} cat /config/home-assistant_v2.db > ${ROOT_DIR}/gen/data/alphaess/homeassistant/home-assistant_v2.db